# Exploring categorical data {#sec-explore-categorical}

::: {.chapterintro data-latex=""}
This chapter focuses on exploring **categorical** data using summary statistics and visualizations.
The summaries and graphs presented in this chapter are created using statistical software; however, since this might be your first exposure to the concepts, we take our time in this chapter to detail how to create them.
Where possible, we present multivariate plots; plots that visualize the relationship between multiple variables.
Mastery of the content presented in this chapter will be crucial for understanding the methods and techniques introduced in the rest of the book.
:::

In this chapter we will work with data on loans from Lending Club that you've previously seen in @sec-data-hello.
The `loan50` dataset from @sec-data-hello represents a sample from a larger loan dataset called `loans`.
This larger dataset contains information on 10,000 loans made through Lending Club.
We will examine the relationship between `homeownership`, which for the `loans` data can take a value of `rent`, `mortgage` (owns but has a mortgage), or `own`, and `app_type`, which indicates whether the loan application was made with a partner or whether it was an individual application.

::: {.data data-latex=""}
The [`loans_full_schema`](http://openintrostat.github.io/openintro/reference/loans_full_schema.html) data can be found in the [**openintro**](http://openintrostat.github.io/openintro) R package.
Based on the data in this dataset we have modified the `homeownership` and `application_type` variables.
We will refer to this modified dataset as `loans`.
:::

## Contingency tables and bar plots

@tbl-loan-home-app-type-totals summarizes two variables: `application_type` and `homeownership`.
A table that summarizes data for two categorical variables in this way is called a **contingency table**.
Each value in the table represents the number of times a particular combination of variable outcomes occurred.

## Visualizing two categorical variables

### Bar plots with two variables

We can display the distributions of two categorical variables on a bar plot concurrently.
Such plots are generally useful for visualizing the relationship between two categorical variables.
@fig-loan-homeownership-app-type-bar-plot shows three such plots that visualize the relationship between `homeownership` and `application_type` variables.
Plot A in @fig-loan-homeownership-app-type-bar-plot is a **stacked bar plot**.
This plot most clearly displays that loan applicants most commonly live in mortgaged homes.
It is difficult to say, based on this plot alone, how different application types vary across the levels of homeownership.
Plot B is a **dodged bar plot**.
This plot most clearly displays that within each level of homeownership, individual applications are more common than joint applications.
Finally, plot C is a **standardized bar plot** (also known as **filled bar plot**).
This plot most clearly displays that joint applications are most common among loans for applicants who live in mortgaged homes, compared to renters and owners.
This type of visualization is helpful in understanding the fraction of individual or joint loan applications for borrowers in each level of `homeownership`.
Additionally, since the proportions of joint and individual loans vary across the groups, we can conclude that the two variables are associated for this sample.

::: {.workedexample data-latex=""}
Examine the three bar plots in @fig-loan-homeownership-app-type-bar-plot.
When is the stacked, dodged, or standardized bar plot the most useful?

------------------------------------------------------------------------

The stacked bar plot is most useful when it's reasonable to assign one variable as the explanatory variable (here `homeownership`) and the other variable as the response (here `application_type`) since we are effectively grouping by one variable first and then breaking it down by the others.

Dodged bar plots are more agnostic in their display about which variable, if any, represents the explanatory and which the response variable.
It is also easy to discern the number of cases in each of the six different group combinations.
However, one downside is that it tends to require more horizontal space; the narrowness of Plot B compared to the other two in @fig-loan-homeownership-app-type-bar-plot makes the plot feel a bit cramped.
Additionally, when two groups are of very different sizes, as we see in the group `own` relative to either of the other two groups, it is difficult to discern if there is an association between the variables.

The standardized stacked bar plot is helpful if the primary variable in the stacked bar plot is relatively imbalanced, e.g., the category has only a third of the observations in the category, making the simple stacked bar plot less useful for checking for an association.
The major downside of the standardized version is that we lose all sense of how many cases each of the bars represents.
:::

### Mosaic plots

A **mosaic plot** is a visualization technique suitable for contingency tables that resembles a standardized stacked bar plot with the benefit that we still see the relative group sizes of the primary variable as well.

To get started in creating our first mosaic plot, we'll break a square into columns for each category of the variable, with the result shown in Plot A of @fig-loan-homeownership-type-mosaic-plot.
Each column represents a level of `homeownership`, and the column widths correspond to the proportion of loans in each of those categories.
For instance, there are fewer loans where the borrower is an owner than where the borrower has a mortgage.
In general, mosaic plots use box *areas* to represent the number of cases in each category.

Plot B in @fig-loan-homeownership-type-mosaic-plot displays the relationship between homeownership and application type.
Each column is split proportionally to the number of loans from individual and joint borrowers.
For example, the second column represents loans where the borrower has a mortgage, and it was divided into individual loans (upper) and joint loans (lower).
As another example, the bottom segment of the third column represents loans where the borrower owns their home and applied jointly, while the upper segment of this column represents borrowers who are homeowners and filed individually.
We can again use this plot to see that the `homeownership` and `application_type` variables are associated, since some columns are divided in different vertical locations than others, which was the same technique used for checking an association in the standardized stacked bar plot.

## Row and column proportions

In the previous sections we inspected visualizations of two categorical variables in bar plots and mosaic plots.
However, we have not discussed how the values in the bar and mosaic plots that show proportions are calculated.
In this section we will investigate fractional breakdown of one variable in another and we can modify our contingency table to provide such a view.
@tbl-loan-home-app-type-row-proportions shows **row proportions** for @tbl-loan-home-app-type-totals, which are computed as the counts divided by their row totals.
The value 3496 at the intersection of individual and rent is replaced by $3496 / 8505 = 0.411,$ i.e., 3496 divided by its row total, 8505.
So, what does 0.411 represent?
It corresponds to the proportion of individual applicants who rent.

Row and column proportions can also be thought of as **conditional proportions** as they tell us about the proportion of observations in a given level of a categorical variable conditional on the level of another categorical variable.

We could also have checked for an association between `application_type` and `homeownership` in @tbl-loan-home-app-type-row-proportions using row proportions.
When comparing these row proportions, we would look down columns to see if the fraction of loans where the borrower rents, has a mortgage, or owns varied across the application types.

::: {.guidedpractice data-latex=""}
What does 0.451 represent in @tbl-loan-home-app-type-row-proportions?
What does 0.802 represent in @tbl-loan-home-app-type-column-proportions?[^04-explore-categorical-1]
:::

[^04-explore-categorical-1]: 0.451 represents the proportion of individual applicants who have a mortgage.
    0.802 represents the fraction of applicants with mortgages who applied as individuals.

::: {.guidedpractice data-latex=""}
What does 0.122 represent in @tbl-loan-home-app-type-row-proportions?
What does 0.135 represent in @tbl-loan-home-app-type-column-proportions?[^04-explore-categorical-2]
:::

[^04-explore-categorical-2]: 0.122 represents the fraction of joint borrowers who own their home.
    0.135 represents the home-owning borrowers who had a joint application for the loan.

::: {.workedexample data-latex=""}
Data scientists use statistics to build email spam filters.
By noting specific characteristics of an email, a data scientist may be able to classify some emails as spam or not spam with high accuracy.
One such characteristic is whether the email contains no numbers, small numbers, or big numbers.
Another characteristic is the email format, which indicates whether an email has any HTML content, such as bolded text.
We'll focus on email format and spam status using the dataset; these variables are summarized in a contingency table.
Which would be more helpful to someone hoping to classify email as spam or regular email for this table: row or column proportions?

------------------------------------------------------------------------

A data scientist would be interested in how the proportion of spam changes within each email format.
This corresponds to column proportions: the proportion of spam in plain text emails and the proportion of spam in HTML emails.

If we generate the column proportions, we can see that a higher fraction of plain text emails are spam ($209/1195 = 17.5\%$) than compared to HTML emails ($158/2726 = 5.8\%$).
This information on its own is insufficient to classify an email as spam or not spam, as over 80% of plain text emails are not spam.
Yet, when we carefully combine this information with many other characteristics, we stand a reasonable chance of being able to classify some emails as spam or not spam with confidence.
This example points out that row and column proportions are not equivalent.
Before settling on one form for a table, it is important to consider each to ensure that the most useful table is constructed.
However, sometimes it simply isn't clear which, if either, is more useful.
:::

::: {.data data-latex=""}
The [email](http://openintrostat.github.io/openintro/reference/email.html) data can be found in the [**openintro**](http://openintrostat.github.io/openintro) R package.
:::


::: {.workedexample data-latex=""}
Look back to @tbl-loan-home-app-type-row-proportions and @tbl-loan-home-app-type-column-proportions.
Are there any obvious scenarios where one might be more useful than the other?

------------------------------------------------------------------------

None that we think are obvious!
What is distinct about the email example is that the two loan variables do not have a clear explanatory-response variable relationship that we might hypothesize.
Usually it is most useful to "condition" on the explanatory variable.
For instance, in the email example, the email format was seen as a possible explanatory variable of whether the message was spam, so we would find it more interesting to compute the relative frequencies (proportions) for each email format.
:::

## Pie charts

A **pie chart** is shown in @fig-loan-homeownership-pie-chart alongside a bar plot representing the same information.
Pie charts can be useful for giving a high-level overview to show how a set of cases break down.
However, it is also difficult to decipher certain details in a pie chart.
For example, it's not immediately obvious that there are more loans where the borrower has a mortgage than rent when looking at the pie chart, while this detail is very obvious in the bar plot.

Pie charts can work well when the goal is to visualize a categorical variable with very few levels, and especially if each level represents a simple fraction (e.g., one-half, one-quarter, etc.).
However, they can be quite difficult to read when they are used to visualize a categorical variable with many levels.
For example, the pie chart and the bar plot in @fig-loan-grade-pie-chart both represent the distribution of loan grades (A through G).
In this case, it is far easier to compare the counts of each loan grade using the bar plot than the pie chart.

## Comparing numerical data across groups

Some of the more interesting investigations can be considered by examining numerical data across groups.
In this section we will expand on a few methods we have already seen to make plots for numerical data from multiple groups on the same graph as well as introduce a few new methods for comparing numerical data across groups.

We will revisit the `county` dataset and compare the median household income for counties that gained population from 2010 to 2017 versus counties that had no gain.
While we might like to make a causal connection between income and population growth, remember that these are observational data and so such an interpretation would be, at best, half-baked.

Color can be used to split histograms (see @sec-histograms for an introduction to histograms) for numerical variables by levels of a categorical variable.
An example of this is shown in Plot A of @fig-countyIncomeSplitByPopGain.
The **side-by-side box plot** is another traditional tool for comparing across groups.
An example is shown in Plot B of @fig-countyIncomeSplitByPopGain, where there are two box plots (see @sec-boxplots for an introduction to box plots), one for each group, placed into one plotting window and drawn on the same scale.

::: {.guidedpractice data-latex=""}
Use the plots in @fig-countyIncomeSplitByPopGain to compare the incomes for counties across the two groups.
What do you notice about the approximate center of each group?
What do you notice about the variability between groups?
Is the shape relatively consistent between groups?
How many *prominent* modes are there for each group?[^04-explore-categorical-3]
:::

[^04-explore-categorical-3]: Answers may vary a little.
    The counties with population gains tend to have higher income (median of about \$45,000) versus counties without a gain (median of about \$40,000).
    The variability is also slightly larger for the population gain group.
    This is evident in the IQR, which is about 50% bigger in the *gain* group.
    Both distributions show slight to moderate right skew and are unimodal.
    The box plots indicate there are many observations far above the median in each group, though we should anticipate that many observations will fall beyond the whiskers when examining any dataset that contain more than a few hundred data points.

::: {.guidedpractice data-latex=""}
What components of each plot in @fig-countyIncomeSplitByPopGain do you find most useful?[^04-explore-categorical-4]
:::

[^04-explore-categorical-4]: Answers will vary.
    The side-by-side box plots are especially useful for comparing centers and spreads, while the hollow histograms are more useful for seeing distribution shape, skew, modes, and potential anomalies.

Another useful visualization for comparing numerical data across groups is a **ridge plot**, which combines density plots (see @sec-boxplots for an introduction to density plots) for various groups drawn on the same scale in a single plotting window.
@fig-countyIncomeSplitByPopGainRidge displays a ridge plot for the distribution of median household income in counties, split by whether there was a population gain or not.

::: {.guidedpractice data-latex=""}
What components of the ridge plot in @fig-countyIncomeSplitByPopGainRidge do you find most useful compared to those in @fig-countyIncomeSplitByPopGain?[^04-explore-categorical-5]
:::

[^04-explore-categorical-5]: The ridge plot give us a better sense of the shape, and especially modality, of the data.

One last visualization technique we'll highlight for comparing numerical data across groups is **faceting**.
In this technique we split (facet) the graphical display of the data across plotting windows based on groups.
Plot A in @fig-countyIncomeSplitByPopGainFacetHist displays the same information as Plot A in @fig-countyIncomeSplitByPopGain, however here the distributions of median household income for counties with and without population gain are faceted across two plotting windows.
We preserve the same scale on the x and y axes for easier comparison.
An advantage of this approach is that it extends to splitting the data across levels of two categorical variables, which allows for displaying relationships between three variables.
In Plot B in @fig-countyIncomeSplitByPopGainFacetHist we have now split the data into four groups using the `pop_change` and `metro` variables:

-   top left represents counties that are *not* in a `metro`politan area with population gain,
-   top right represents counties that are in a metropolitan area with population gain,
-   bottom left represents counties that are *not* in a metropolitan area without population gain, and finally
-   bottom right represents counties that are in a metropolitan area without population gain.

::: {.guidedpractice data-latex=""}
Based on @fig-countyIncomeRidgeMulti, what can you say about how median household income in counties vary depending on population gain/no gain, metropolitan area/not, and median degree?[^04-explore-categorical-6]
:::

[^04-explore-categorical-6]: Regardless of the location (metropolitan or not) or change in population, it seems like there is an increase in median household income from individuals with only a HS diploma, to individuals with some college, to individuals with a Bachelor's degree.

\vspace{20mm}

## Chapter review {#sec-chp4-review}

### Summary

Fluently working with categorical variables is an important skill for data analysts.
In this chapter we have introduced different visualizations and numerical summaries applied to categorical variables.
The graphical visualizations are even more descriptive when two variables are presented simultaneously.
We presented bar plots, mosaic plots, pie charts, and estimations of conditional proportions.

### Terms

We introduced the following terms in the chapter.
If you're not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We are purposefully presenting them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate.
However, you should be able to easily spot them as **bolded text**.

\clearpage