## Ayat 104

[O You Who Believe!]{style="background-color: green"}
Say not (to the Messenger Peace be upon him) Râ'ina but say Unzurna (Do make us understand) and hear.
And for the disbelievers, there is a painful torment.
(See Verse 4:46)

### Causes of Revelation

#### Al-Suyuti

It is narrated on the authority of As-Suddi that he said: Whenever Malik Ibn As-Sayf and Rifa'ah Ibn Zayd, among the Jews, met The Messenger of Allah \[peace be upon him\], they would say to him: "Hear but be not heard" and "Ra'ina." The Muslims, having thought those expressions had been used by the men of Scripture to exalt and honor their Prophets, said the same to The Messenger of Allah \[peace be upon him\].
On that occasion, Allah Almighty revealed this Qur'anic Verse.
\[Ibn Al-Mundhir\] It is narrated on the authority of lbn 'Abbas \[Allah be pleased with them\] that he said: Ra'ina according to the Jews meant a bad abuse.
When they heard the Companions of The Messenger of Allah \[peace be upon him\] saying this to him, they used to say it and laugh among themselves.
After this Qur'anic Verse had been revealed, Sa'd Ibn Mu'adh \[Allah be pleased with him\] heard it from them, thereupon he said to the Jews: "O enemies of Allah! If I hear this from any one of you after this gathering, I will chop off his head".
\[Abu Na'im in Ad-Dala'il\]

#### Al-Wahidi

Said Ibn 'Abbas according to the narration of 'Ata': "This is because the Arabs used to employ this expression \[ra'ina\], so when the Jews heard them using it with the Prophet, Allah bless him and give him peace, they liked it. This same expression in the vocabulary of the Jews had the connotation of vile abusive language. They said: 'Before, we used to abuse Muhammad secretly. Now, you can abuse him openly because this expression is used in their speech. Therefore, they used to come to Allah's Prophet, Allah bless him and give him peace, and say: 'O Muhammad! ra'ina', and they would laugh. A man from the Helpers --- Sa'd ibn 'Ubadah who understood well the language of the Jews---understood the reason. He said to them: 'O enemies of Allah! May Allah's curse be on you. By Him in Whose Hand is Muhammad's soul, I will cut the head of any man of you who utters this expression'. They objected, saying: 'But do you not use the same expression with him?' And therefore Allah, exalted is He, revealed: (O ye who believe, say not (unto the Prophet):"Listen to us" \[ra'ina\]) but say "Look upon us" \[unzurna\]...).

### Tafsir

#### Al-Jalalain

O you who believe, do not say, to the Prophet (S.A.W.), 'Observe us', (rahina is an imperative form from mura.at) which they used to say to him, and this was a derogatory term in Hebrew, derived from the noun al-ruhuna \['thoughtlessness\].
They found this very amusing and used to address the Prophet (.) in this way, and so the believers were forbidden to use it; but say, instead, 'Regard us', that is, look at us, and give ear, to what you are commended and be prepared to accept it; and for the disbelievers awaits a painful chastisement, that is, the Fire.

#### Al-Qurtubi

This is talking about another act of ignorance on the part of the Jews and the purpose is to forbid Muslims from doing the same thing.
The meaning of ra'ina is 'look at us and we will look at you' because the form of the verb dictates that.
It further signifies 'protect us and we will protect you; watch us and we will watch you.' Using this word, however, entails coarseness and the believers were commanded to choose a better word with a finer meaning.
Ibn 'Abbas said, 'The Muslims used to say to the Prophet (saw), "Ra'ina!" by way of asking and desire, from mura'ah (supervision, respect).
In Hebrew it was a curse, meaning "Listen, you do not hear." So, the Jews took advantage of that and said, "We curse him secretly. Now we will curse him openly!" and they used to use the word to address the Prophet and then laugh about it.
Sa'd ibn Mu'adh overheard them because he knew their language.
He told them, "The curse of Allah is on you! If I hear a single man of you say it to the Prophet (S.A.W), I will lop his head off!" They replied, "But you say it!" Then the ayah was revealed, and they were forbidden to do it so that the Jews would not imitate them and intend a bad meaning by it.' This ayah contains evidence for two rulings.
One is that you should avoid ambiguous expressions that could be disparaging or allude to faults.
A corollary of this is that slander can be by allusion and we say that doing this obliges the hadd punishment whereas Abu Hanifah and ash-Shafi'i said that the aspect of doubt involved removes the .add.
This will be discussed in an Nur.
The second ruling to be gained from the ayah is that sadd adh dhara'i' (the blocking of the means), and the protection it gives, constitutes a valid legal principle, which is the position of Malik and also of Ahmad ibn Hanbal in one transmission from him.
The Book and Sunnah provide evidence for this principle.
Dhari'ah (means) is something that is not prohibited in itself but it is feared that someone who does it will fall into the prohibited.
In the Qur'an, this ayah demonstrates the principle.
The way the principle is applied here is that the Jews used to say this phrase, which was a curse in their language.
Then Allah informed the Muslims about it and issued the prohibition of the use of this phrase because, although it is all right, it is the means to the evil result.

